In [1]:
'''
import library numpy agar dapat membuat matrix dan melakukan perhitungan

'''

import numpy as np

1. Buatlah Tensor menggunakan nilai yang sudah ditentukan dengan Python

In [2]:
'''
Membuat tensor sesuai dengan nilai yang ada pada guidlines non-graded challenge 4

'''

tensor = np.array([[[23,50], [7,12], [75,21], [57,12]], [[57,67], [99,43], [87,26], [18,84]]])
print(tensor.shape)
print(tensor)

(2, 4, 2)
[[[23 50]
  [ 7 12]
  [75 21]
  [57 12]]

 [[57 67]
  [99 43]
  [87 26]
  [18 84]]]


2. Lakukan perkalian terhadap matrix A dan matrix B berikut:

In [3]:
'''
Membuat matrix A dan matrix B terlebih dahulu

'''


A = np.array([[23,50,19], [7,12,109], [57,67,98]])
B = np.array([[17,22,19]])

In [4]:
'''
Perkalian matrix A dengan matrix B

'''


print(B.dot(A))

[[1628 2387 4583]]


3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix A

In [5]:
'''
Membuat matrix A sesuai nilai yang ditentukan di guidlines non-graded challenge

'''

A = np.array([[23,50,19], [7,12,109], [57,67,98]])

In [6]:
'''
Menampilkan matrix A, melakukan transpose matrix A, dan menampilkan hasil matrix
A setelah ditranspose

'''
print(A)
print('transpose:\n', A.T)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
transpose:
 [[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [7]:
'''
Import det dan inv dari library numpy agar dapat melakukan perhitungan 
invers dan determinant

'''

from numpy.linalg import det
from numpy.linalg import inv

In [8]:
'''
Melakukan determinant matrix A

'''
det(A)

131344.0000000002

In [9]:
'''
Melakukan invers matrix A

'''
inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])