In [ ]:
'''
Import library numpy untuk digunakan dalam mendefinisikan matrix

Import perintah eig dari library numpy.linalg untuk digunakan dalam mencari
eigen value dan eigen vector

'''

import numpy as np
from numpy.linalg import eig

In [ ]:
'''
Mendefinisikan Matrix

'''

matrix = np.array([[1, -1], [6,4]])

In [ ]:
'''
Menghitung nilai eigen value dan eigen vector

'''
eigVal, eigVec = eig(matrix)

In [ ]:
'''
Menampilkan eigen value

'''
eigVal

array([2.5+1.93649167j, 2.5-1.93649167j])

In [ ]:
'''
Menampilkan eigen vector

'''

eigVec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

In [ ]:
'''
Reconstruct matrix

'''

Z = eigVec@np.diag(eigVal)@np.linalg.inv(eigVec)

In [ ]:
'''
Menampilkan nilai Z

'''

Z

array([[ 1.+1.40042907e-16j, -1.-1.64348860e-17j],
       [ 6.+2.45405006e-16j,  4.+1.39206967e-17j]])

In [ ]:
np.allclose(matrix, Z)

True